### PR TITLE
Add a script to view books locally

### PR DESCRIPTION
**Pull request by laras126**
This PR includes the addition of a small shell script to that opens the a book for local viewing on a server. It does the following, given a path to a book –
* Run `npm run build-test` to compile assets,
* Copy build the build directory to the path of a book so the assets are available locally, 
* Start an HTTP server in a given path and open a browser window.

To test it, clone the repository and run the following commands:
```
$ npm install
$ npm run book -- examples/tutorial
```

This PR also includes creating the build directory in a `postinstall` script which is run automatically by npm after dependencies are installed.

@amyjko – Some info about me / my reasons for contributing: I have been learning a lot from your work as I research for a book I am writing. I've thinking about building something like Peruse for myself, then I encountered it via your website and thought I'd try it out! I had some difficulty viewing the tutorial when I cloned the repo, so here is a PR with my solution in case it is useful to the project.

### CODE REVIEW

**Comment by laras126** [comment]
Actually...I had an for a more useful script, `npm run book`, that does the same thing but instead you can pass a path argument and it will start a local server for any book in any location, not just the tutorial example. I'm close this PR and open another with that!

**Comment by amyjko** [comment]
Thanks for contributing! As you can probably tell (especially in the backlog), this is just barely ready for hosting books, and not at all ready for others to use seamlessly :) Thanks for helping nudge it closer!

**Comment by laras126** [comment]
> Thanks for contributing! As you can probably tell (especially in the backlog), this is just barely ready for hosting books, and not at all ready for others to use seamlessly :) Thanks for helping nudge it closer!

You're welcome! I think I closed the PR right as you were posting a message, oops :D I'm thinking that was premature and I can just update this one with new details – re-opening!!

**Review by amyjko — APPROVED** [review]
This looks great, thanks for the contribution!

**Pull request merged**
